### ISSUE TITLE
Cannot prevent from running in submodules

### ISSUE THREAD

**Issue by jflamy** [RagedUnicorn/github-release-maven-plugin#1]
I have a project with submodules.   When calling the release goal, there is recusion to the submodules.  The plugin does not conform to the `<inherit>false</inherit>` rule that is supposed to prevent recursion.  

The recursion is not wanted in any case , because the Tag already exists when the child is called, so there is nothing useful that can be done by the child module.

The other tricks (using an empty execution phase on the child, or adding <skip>true</skip> on the child do not work.

**Comment by RagedUnicorn** [comment]
Hi @jflamy,

I'm not sure if I understand. As far as I can see there is not work needed by the plugin to support the inherit flag. I think you might have a misstype in there. The flag is actually called `inherited`

The following seems to be working for me without a problem:
```
<inherited>false</inherited>
```
I used an example maven module that had about 6 submodules and the plugin definition for the release plugin was set in the project pom (topmost level).

It would execute the plugin on the project itself but not on the submodules. When I removed the inherited flag I ran into the same problem. Essentially what you described both tag and release already exist and the GitHub Api would respond with an appropriate error.

![Screenshot 2019-10-04 at 12 48 05](https://user-images.githubusercontent.com/26184132/66202502-31719e00-e6a6-11e9-9d9c-5a7f611babf4.png)

See maven documentation: https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_inherited_Tag_In_Build_Plugins


Cheers,
RagedUnicorn

**Comment by jflamy** [comment]
Here is what I have
You will notice that the first plugin calls the github-release goal.
Apparently, inherited (which I had correct in the actual pom) is something
that the reactor looks at, and that doesn't seem to work when calling a
goal in this fashion. So I'm sort of stuck with using the skip hack.
Thanks for replying.

            <plugin>
                <groupId>com.amashchenko.maven.plugin</groupId>
                <artifactId>gitflow-maven-plugin</artifactId>
                <version>1.12.0</version>
                <configuration>
                    <allowSnapshots>true</allowSnapshots>
                    <preReleaseGoals>verify</preReleaseGoals>

<postReleaseGoals>github-release:github-release</postReleaseGoals>
                    <skipTag>true</skipTag>
                    <skipTestProject>true</skipTestProject>

<commitDevelopmentVersionAtStart>true</commitDevelopmentVersionAtStart>
                    <verbose>true</verbose>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.ragedunicorn.tools.maven</groupId>
                <artifactId>github-release-maven-plugin</artifactId>
                <version>1.0.2-SNAPSHOT</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <configuration>
                            <owner>jflamy</owner>
                            <repository>owlcms4</repository>
                            <server>github-oauth</server>
                            <tagName>${project.version}</tagName>
                            <name>${project.version}</name>
                            <targetCommitish>master</targetCommitish>
                            <body>${project.version}</body>
                            <releaseNotes>ReleaseNotes.md</releaseNotes>
                            <assets>
                                <asset>owlcms/target/owlcms.zip</asset>

<asset>owlcms/target/owlcms_setup/owlcms_setup.exe</asset>
                            </assets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

Le ven. 4 oct. 2019 à 06:56, Raged Unicorn <notifications@github.com> a
écrit :
